name: Build & Deploy
on:
  push:
    branches:
      - main
env:
  SKIP_PREFLIGHT_CHECK: true

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    # - name: Look Changelog
    #   uses: jaywcjlove/changelog-generator@v1.6.2
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     filter-author: (小弟调调™|Renovate Bot)
    #     filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - run: npm install
    - run: npm run build

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.5
      with:
        package-path: ./core/package.json

    - name: Generate changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.6.2
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (小弟调调™|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: jaywcjlove/create-tag-action@v1.3.5
      with:
        package-path: ./core/package.json
        release: true
        body: |
          ```bash
          npm i carefree-proload@${{steps.changelog.outputs.version}}
          ```

          ${{ steps.changelog.outputs.compareurl }}

          ${{ steps.changelog.outputs.changelog }}

    - run: echo ${{ steps.changelog.outputs.tag }}

    # - name: 📦 carefree-proload publish to NPM
    #   uses: kktjs/npm-publish@main
    #   with:
    #     token: ${{ secrets.NPM_TOKEN }}
    #     package: ./core/package.json
